# This is a basic workflow to help you get started with Actions

name: Copy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "dev/a.txt"
          target: "test-a.txt"
